### ISSUE TITLE
Assign __FILE__ or some other variable prior inlined file with relative path.

### ISSUE THREAD

**Issue by jlewallen** [intervalia/gulp-component-assembler#2]
It would be nice if prior to the inline content of a js file the bundler would assign a __FILE__ variable, like so:

/*
 * Included File: some-directory/some-file.js
 */
var __FILE__= "some-directory/some-file.js";

<FILE GOES HERE>

/*
 * Included File: some-directory/another-file.js
 */
var __FILE__= "some-directory/another-file.js";

<ANOTHER FILE GOES HERE>

And so on...  this would help when dealing with bundled js that uses AMD, for example.

**Comment by intervalia** [comment]
This can now be accomplished by using the `plugins/fileNameProvider.js` plug-in.
