### ISSUE TITLE
Would like to understand development time vs build time workflow

### ISSUE THREAD

**Issue by divyakumarjain** [intervalia/gulp-component-assembler#5]
If i understand it correctly assembler will provide produce single file as a final output. Is there a different workflow during development like using non assembled and non minified during unit testing and debugging in application in browser.

**Comment by intervalia** [comment]
Yes, the primary goal of the component-assembler is to combine several files into one. JavaScript, HTML Templates and Locale strings can be included.

Most of the time when we do unit testing we load the source files independently and we tend to use PhantomJS. But sometimes we also expose certain functions in the assembled file and only test those.
