### ISSUE TITLE
Better docs and interface to plugins

### ISSUE THREAD

**Issue by lambertsteven** [intervalia/gulp-component-assembler#8]
Docs are currently lacking on how to get and use any of the plugins that are available in the plugins directory (need to require them using `require('./node_modules/gulp-component-assembler/plugins/oldTemplates.js')`). If the require statement could be made shorter, or maybe just attaching the plugins to the component assembler, that would be nice too.

**Comment by intervalia** [comment]
resolved by 5348b67ac1791272b0f57ea1eebfb6691f2dd1c2
